name: kuis_uts
description: Aplikasi kuis IT untuk mahasiswa baru
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/loggo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/loggo.png"

